---
- name: Pull Docker images
  become: yes
  command: "kubeadm config images pull"
  tags:
    - k8s

- name: Ensure kubeadm initialization
  become: yes
  command: "kubeadm init --pod-network-cidr=172.43.0.0/16 --apiserver-advertise-address=192.168.1.11"
  tags:
    - k8s

- name: Copy dashboard rbac config
  become: yes
  copy:
    content: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: admin-user
        namespace: kubernetes-dashboard
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: admin-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: admin-user
        namespace: kubernetes-dashboard
    dest: /var/tmp/dashboard-rbac-config.yaml
  tags:
    - k8s

- name: Copy StorageClass config
  become: yes
  copy:
    content: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: hostpath
      provisioner: kubernetes.io/no-provisioner
      volumeBindingMode: WaitForFirstConsumer
      ---
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: standatd
      provisioner: kubernetes.io/no-provisioner
      volumeBindingMode: WaitForFirstConsumer
    dest: /var/tmp/storageclass-config.yaml
  tags:
    - k8s

- name: Copy config to /Vagrant for other VMs
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /vagrant/admin.conf
    owner: vagrant
    group: vagrant
    mode: 0600
  tags:
    - k8s

- name: Copy config to home directory
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/admin.conf
    owner: vagrant
    group: vagrant
    mode: 0600
  tags:
    - k8s

- name: Update Environment
  become: yes
  lineinfile:
    path: /home/vagrant/.bashrc
    regexp: '^export KUBECONFIG='
    line: 'export KUBECONFIG=/home/vagrant/admin.conf'
    state: present
  tags:
    - k8s

- name: Ensure Calico network file
  become: yes
  get_url:
    url: https://docs.projectcalico.org/v3.10/manifests/calico.yaml
    dest: /var/tmp/calico.yaml
    mode: 0444
  tags:
    - k8s

- name: Ensure Calico CIDR
  become: yes
  replace:
    path: /var/tmp/calico.yaml
    regexp: '192.168.0.0\/16'
    replace: '172.43.0.0/16'
    backup: yes
  tags:
    - k8s

- name: Ensure Network Start Scripts
  become: yes
  copy:
    src: files/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - "start-calico"
  tags:
    - k8s

- name: Ensure Utility Scripts
  become: yes
  copy:
    src: files/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - "dashboard-token"
    - "kubeadm-hash"
    - "kubeadm-token"
    - "taint-nodes"
    - "create-storage-class"
    - "create-join-script"
    - "docker-registry-create"
    - "docker-registry-delete"
  tags:
    - k8s

- name: Ensure Kube directory
  become: yes
  file:
    path: /home/vagrant/.kube
    state: directory
  tags:
    - k8s

- name: Copy config to Kube directory
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode: 0600
  tags:
    - k8s

- name: List Kubernetes nodes
  become: yes
  command: "kubectl --kubeconfig=/home/vagrant/admin.conf get nodes"
  register: nodes
  tags:
    - k8s
- debug: var=nodes.stdout_lines

- name: Ensure dashboard file
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml
    dest: /var/tmp/kubernetes-dashboard.yaml
    mode: 0444
  tags:
    - k8s

- name: Install dashboard service
  become: yes
  command: "kubectl --kubeconfig=/home/vagrant/admin.conf apply -f /var/tmp/kubernetes-dashboard.yaml"
  tags:
    - k8s

- name: Install dashboard rbac
  become: yes
  command: "kubectl --kubeconfig=/home/vagrant/admin.conf apply -f /var/tmp/dashboard-rbac-config.yaml"
  tags:
    - k8s

- name: Ensure Helm files
  become: yes
  get_url:
    url: https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz
    dest: /var/tmp/helm.tar.gz
    mode: 0444
  tags:
    - k8s

- name: Create Helm directory
  become: yes
  file:
    path: /var/tmp/helm
    state: directory
  tags:
    - k8s

- name: Decompress Helm files
  become: yes
  unarchive:
    src: /var/tmp/helm.tar.gz
    dest: /var/tmp/helm
  tags:
    - k8s

- name: Install helm command
  become: yes
  command: "cp /var/tmp/helm/linux-amd64/helm /usr/local/bin"
  tags:
    - k8s

- name: Ensure Metrics server files
  become: yes
  git:
    repo: 'https://github.com/kubernetes-incubator/metrics-server.git'
    dest: /var/tmp/metrics-server
  tags:
    - k8s

- name: List Metrics server directory
  become: yes
  command: "ls -al /var/tmp/metrics-server"
  register: lstmp
  tags:
    - k8s
- debug: var=lstmp.stdout_lines

- name: Modify Metrics server deployment
  become: yes
  blockinfile:
    dest: /var/tmp/metrics-server/deploy/kubernetes/metrics-server-deployment.yaml
    insertafter: 'imagePullPolicy: IfNotPresent'
    block: "        command: ['/metrics-server', '--kubelet-insecure-tls', '--kubelet-preferred-address-types=InternalIP']"
    backup: yes
  tags:
    - k8s

- name: Change runAsRoot in Metrics server deployment
  become: yes
  replace:
      path: /var/tmp/metrics-server/deploy/kubernetes/metrics-server-deployment.yaml
      regexp: 'runAsNonRoot: true'
      replace: 'runAsNonRoot: false'
  tags:
    - k8s

- name: Print Metrics server deployment
  become: yes
  command: "cat /var/tmp/metrics-server/deploy/kubernetes/metrics-server-deployment.yaml"
  register: cat
  tags:
    - k8s
- debug: var=cat.stdout_lines

- name: Install Metrics server
  become: yes
  command: "kubectl --kubeconfig=/home/vagrant/admin.conf create -f /var/tmp/metrics-server/deploy/kubernetes/"
  tags:
    - k8s

- name: Create join script
  become: yes
  command: "create-join-script"
  tags:
    - k8s

- name: Copy join script
  become: yes
  copy:
    src: /home/vagrant/join.sh
    dest: /vagrant/join.sh
    owner: vagrant
    group: vagrant
    mode: 0600
  tags:
    - k8s

- name: Create Docker Registry data directory
  become: yes
  file:
    path: /var/tmp/docker-registry/data
    state: directory
  tags:
    - k8s

- name: Create Docker Registry certs directory
  become: yes
  file:
    path: /var/tmp/docker-registry/certs
    state: directory
  tags:
    - k8s

- name: Create Docker Registry auth directory
  become: yes
  file:
    path: /var/tmp/docker-registry/auth
    state: directory
  tags:
    - k8s

- name: Copy Docker Registry files
  become: yes
  copy:
    content: |
      ---
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pv-docker-registry
        labels:
          app: registry
      spec:
        storageClassName: hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        selector:
            matchLabels:
              app: registry
      ---
      apiVersion: v1
      kind: Pod
      metadata:
        name: registry
        labels:
          app: registry
      spec:
        containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /var/lib/registry
              subPath: data
              name: registry-data
            - mountPath: /etc/certs
              subPath: certs
              name: registry-data
            - mountPath: /etc/auth
              subPath: auth
              name: registry-data
          env:
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:5000"
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/etc/certs/docker-registry.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/etc/certs/docker-registry.key"
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/etc/auth/htpasswd"
        volumes:
          - name: registry-data
            persistentVolumeClaim:
              claimName: pv-docker-registry
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - k8s1
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: registry
        labels:
          app: registry
      spec:
        selector:
          app: registry
        ports:
          - port: 5000
            targetPort: 5000
            nodePort: 30000
        type: NodePort
      ---
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: pv-docker-registry
        labels:
          app: registry
      spec:
        capacity:
          storage: 5Gi
        accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: hostpath
        local:
          path: /var/tmp/docker-registry
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s1
    dest: /var/tmp/docker-registry.yaml
  tags:
    - k8s

- name: Create SSL config for Docker Registry
  become: yes
  copy:
    content: |
      [req]
      distinguished_name = distinguished_name_req
      [distinguished_name_req]
      [v3_ca]
      subjectAltName = IP:192.168.1.11
    dest: /var/tmp/docker-registry-ssl.conf
  tags:
    - k8s

- name: Generate Docker Registry Self-signed Certificate
  become: yes
  shell: |
      openssl req -config /var/tmp/docker-registry-ssl.conf -extensions v3_ca -newkey rsa:4096 -nodes -sha256 -keyout /var/tmp/docker-registry.key -x509 -days 365 -subj "/CN=192.168.1.11" -out /var/tmp/docker-registry.crt
      openssl x509 -text -in /var/tmp/docker-registry.crt
      mkdir -p /etc/docker/certs.d/192.168.1.11:30000
      cp /var/tmp/docker-registry.crt /etc/docker/certs.d/192.168.1.11:30000/ca.crt
      mv /var/tmp/docker-registry.crt /var/tmp/docker-registry/certs
      mv /var/tmp/docker-registry.key /var/tmp/docker-registry/certs
  args:
    executable: /bin/bash
  tags:
    - k8s

- name: Generate Docker Registry authentication config
  become: yes
  shell: |
      docker run --rm --entrypoint htpasswd registry:2 -Bbn test password > /var/tmp/htpasswd
      mv /var/tmp/htpasswd /var/tmp/docker-registry/auth/htpasswd
  args:
    executable: /bin/bash
  tags:
    - k8s

- name: Copy Docker Registry Self-signed Certificate
  become: yes
  shell: |
      cp /var/tmp/docker-registry/certs/docker-registry.crt /vagrant
  args:
    executable: /bin/bash
  tags:
    - k8s
